name: .NET Core Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.300
    - name: Build BlazorWasmDynamicPermissions
      run: dotnet build ./src/Server/BlazorWasmDynamicPermissions.Server.csproj --configuration Release